/* Generated By:JavaCC: Do not edit this line. AdvancedCalculatorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdvancedCalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Number = 22;
  /** RegularExpression Id. */
  int Variable = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"sin(\"",
    "\"cos(\"",
    "\"tan(\"",
    "\"sqrt(\"",
    "\"pow(\"",
    "\",\"",
    "\"printMemory()\"",
    "<Number>",
    "<Variable>",
  };

}
